routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index']);

Route::resource('companies' , CompanyController::class);

Route::resource('employees' , EmployeeController::class);

require __DIR__.'/auth.php';

app/Models/company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class company extends Model
{
    use HasFactory;
    protected $fillable = ['name','email','logo','website'];

    public static function InsertImages($images, $folder)
    {
        $image_path = $folder;
        $path = public_path() . $image_path;
        $filename = time().'_'.rand(000 ,999).'.'.$images->getClientOriginalExtension();
        $images->move($path, $filename);
        $paths = $image_path.'/'.$filename;
        return $paths;
    }

    public function employee() {
        return $this->hasMany(employee::class);
    }

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;
use App\Models\company;
use DataTables;

use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax()){
            return DataTables::eloquent(company::query())
            ->addColumn('image', function($data)
                {
                    $url = url('/').$data->logo;
                    return $url;
                })
            ->addIndexColumn()->make(true);
        }
        return view('companies.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'unique:companies',
            // "logo"  => "dimensions:['image','mimes:jpg,png,jpeg,gif','max_width=100,max_height=100']",
        ]);
        company::create([
            'name' => $request->name,
            'email' => $request->email,
            'logo' => !empty($request->file('logo')) ? company::InsertImages($request->file('logo'),'/company_images') : '',
            'website' => $request->website,
        ]);

        $details = [
            'title' => 'This is test mail',
            'body' => $request->name .' / '. $request->email,
        ];

        \Mail::to($request->email)->send(new \App\Mail\MyTestMail($details));
        
        return redirect('companies')->with(['add_message' => 'Record Added Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::where('id',$id)->first();
        return view('companies.edit',get_defined_vars());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'unique:companies,email,'.$id,
            // "logo"  => "dimensions:['image','mimes:jpg,png,jpeg,gif','max_width=100,max_height=100']",
        ]);
        $company = Company::find($id);
        $company->name = $request->name;
        $company->email = $request->email;
        $company->logo = !empty($request->file('logo')) ? company::InsertImages($request->file('logo'),'/company_images') : '';
        $company->website = $request->website;
        $company->update();
        return redirect('companies')->with(['update_message' => 'Company Updated Successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $company = Company::find($id);
            $company->delete();
            return ['code'=>'200','message'=>'success'];
        }
        catch(\Exception $e){
            return ['code'=>'500','error_message'=>$e->getMessage()];
        }
    }
}

resources/views/companies/add.blade.php
@extends('layout.master')
@section('title', 'add company')
@section('main')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Company Form</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('companies.index')}}">List</a></li>
              <li class="breadcrumb-item active">Add New Company</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add New Company</h3>
              </div>
              <form class="form" action="{{route('companies.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <ul class="list-unstyled">
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                </ul>
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name :</label>
                    <input type="text" class="form-control" name="name" id="name" placeholder="Enter company Name" value="{{ old('name', '') }}">
                  </div>
                  <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" value="{{ old('email', '') }}">
                  </div>
                  <div class="form-group">
                    <label for="logo">Logo</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="logo" class="custom-file-input" id="logo" value="{{ old('logo', '') }}" accept="image/png, image/gif, image/jpg, image/jpeg"  >
                        <label class="custom-file-label" for="logo">Choose Logo</label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="website">website</label>
                    <input type="text" class="form-control" name="website" id="website" placeholder="enter website" value="{{ old('website', '') }}">
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
@endsection

resources/views/companies/edit.blade.php
@extends('layout.master')
@section('title', 'add company')
@section('main')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Company Form</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('companies.index')}}">List</a></li>
              <li class="breadcrumb-item active">Add New Company</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add New Company</h3>
              </div>
              <form class="form" action="{{route('companies.update',$company->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <ul class="list-unstyled">
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                </ul>
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">Name :</label>
                    <input type="text" class="form-control" name="name" id="name" placeholder="Enter company Name" value="{{ old('name', $company->name) }}">
                  </div>
                  <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" value="{{ old('email', $company->email) }}">
                  </div>
                  <div class="form-group">
                    <label for="logo">Logo</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="file" name="logo" class="custom-file-input" id="logo" value="{{ old('logo', $company->logo) }}">
                        <label class="custom-file-label" for="logo">Choose Logo</label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <img src="{{asset($company->logo)}}" alt="" width="100px" height="100px">
                  </div>
                  <div class="form-group">
                    <label for="website">website</label>
                    <input type="text" class="form-control" name="website" id="website" placeholder="enter website" value="{{ old('website', $company->website) }}">
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
@endsection

resources/views/companies/index.blade.php
@extends('layout.master')
@section('title', 'Companies List')
@section('main')
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Companies List</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('companies.index')}}">List</a></li>
            <li class="breadcrumb-item active"></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              {{-- <div class="card-header">
                <h3 class="card-title">DataTable with minimal features & hover style</h3>
              </div> --}}
              <!-- /.card-header -->
              <div class="card-body">
                <table>
                    <table id="dataTable" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Sr No</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Logo</th>
                                <th>Website</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
  </section>

@endsection

@section('script')
    @if(Session::has('add_message'))    
        <script>
            Toast.fire({
                icon: 'success',
                title: 'Company Added Successfully.'
            });
        </script>
    @endif
    @if(Session::has('update_message'))
        <script>
            Toast.fire({
                icon: 'success',
                title: 'Company Updated Successfully.'
            });
        </script>
    @endif

    <script>
         var dataTable;
        $(document).ready(function(){
            dataTable = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('companies.index') }}",
                columns: [
                    {
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex',
                        searchable: false,
                        orderable: false
                    },
                    {
                        data: 'name'
                    },
                    {
                        data: 'email',
                    },
                    { data: "image", "render": function (data){
                        return '<img src="'+data+'" style="height:80px;width:100px;"/>'
                    }},
                    // {
                    //     data: 'logo',
                    // },
                    {
                        data: 'website',
                    },
                    {
                        data: '',
                    },
                ],
                "columnDefs": [
                    {
                        // Actions
                        targets: -1,
                        searchable:false,
                        orderable: false,
                        render: function(data, type, full, meta) {
                            return (
                                '<a href="{{url("companies/")}}'+"/"+full.id+'/edit" class="btn btn-sm btn-outline-primary me-1"><i class="far fa-edit nav-icon"></i></a>'+
                                '<a href="javascript:;" class="btn btn-sm btn-outline-danger" onclick="deleteCompany('+full.id+
                                ')"><i class="fa fa-trash nav-icon"></i></a>'
                            );
                        }
                    },
                    {
                        "defaultContent": "-",
                        "targets": "_all"
                    }
                ],
            });
        });

        function deleteCompany(id) {
            var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
            });
            if(confirm('Are you sure you want to delete!'))
            {
                $.ajax({
                    url: "companies/" + id,
                    type: "DELETE",
                    data: {
                        _token: "{{ csrf_token() }}"
                    },
                    success: function(response) {
                        if (response.error_message) {
                            Toast.fire({
                                icon: 'error',
                                title: 'Contact Admin! Somthing went wrong.'
                            });
                        }
                        else {
                            Toast.fire({
                                icon: 'success',
                                title: 'Company Updated Successfully.'
                            });
                            dataTable.ajax.reload();
                        }
                    }
                });
            }
        }
    </script>
@endsection