routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index']);

Route::resource('companies' , CompanyController::class);

Route::resource('employees' , EmployeeController::class);

require __DIR__.'/auth.php';

app/Models/employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class employee extends Model
{
    use HasFactory;
    protected $fillable = ['first_name','last_name','company_id','email','phone'];
    
    public function company() {
        return $this->belongsTo(company::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\employee;
use App\Models\company;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = employee::with(['company'])->get();
        return view('employees.index',get_defined_vars());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = company::select('id','name')->get();
        return view('employees.add',get_defined_vars());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'unique:employees',
        ]);
        
        employee::create([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'company_id' => $request->company_id,
            'email' => $request->email,
            'phone' => $request->phone,
        ]);
        return redirect('employees')->with(['add_message' => 'Record Added Successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $companies = company::select('id','name')->get();
        $employee = employee::where('id',$id)->first();
        // dd($employee);
        return view('employees.edit',get_defined_vars());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'unique:employees,email,'.$id,
        ]);

        $company = employee::find($id);
        $company->first_name = $request->first_name;
        $company->last_name = $request->last_name;
        $company->company_id = $request->company_id;
        $company->email = $request->email;
        $company->phone = $request->phone;
        $company->update();

        return redirect('employees')->with(['update_message' => 'Company Updated Successfully.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         try{
            $company = employee::find($id);
            $company->delete();
            return ['code'=>'200','message'=>'success'];
        }
        catch(\Exception $e){
            return ['code'=>'500','error_message'=>$e->getMessage()];
        }
    }
}

resources/views/employees/add.blade.php
@extends('layout.master')
@section('title', 'add Employee')
@section('main')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Employee Form</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('employees.index')}}">List</a></li>
              <li class="breadcrumb-item active">Add New Employee</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Add New Employee</h3>
              </div>
              <form class="form" action="{{route('employees.store')}}" method="POST">
                @csrf
                <ul class="list-unstyled">
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                </ul>
                <div class="card-body">
                    <div class="form-group">
                        <label for="first_name">First Name :</label>
                        <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Enter First Name" value="{{ old('first_name', '') }}">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name :</label>
                        <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter Last Name" value="{{ old('last_name', '') }}">
                    </div>
                    <div class="form-group">
                        <label for="company">Select Company :</label>
                        <select class="form-select form-control" id="company" name="company_id">
                            <option selected>Select Company :</option>
                            @foreach ($companies as $key => $company)
                                <option value="{{$company->id}}">{{$company->name}}</option>
                            @endforeach
                        </select>
                    </div>
                  
                  <div class="form-group">
                    <label for="email">Email address :</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" value="{{ old('email', '') }}">
                  </div>
                  <div class="form-group">
                    <label for="phone">Phone :</label>
                    <input type="number" class="form-control" name="phone" id="phone" placeholder="enter phone Number" value="{{ old('phone', '') }}">
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
@endsection

resources/views/employees/edit.blade.php
@extends('layout.master')
@section('title', 'Update Employee')
@section('main')
 <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Employee Update Form</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('employees.index')}}">List</a></li>
              <li class="breadcrumb-item active">Update Employee</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Update Employee</h3>
              </div>
              <form class="form" action="{{route('employees.update',$employee->id)}}" method="POST">
                @csrf
                @method('PUT')
                <ul class="list-unstyled">
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                </ul>
                <div class="card-body">
                    <div class="form-group">
                        <label for="first_name">First Name :</label>
                        <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Enter First Name" value="{{ old('first_name', $employee->first_name) }}">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name :</label>
                        <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Enter Last Name" value="{{ old('last_name', $employee->last_name) }}">
                    </div>
                    <div class="form-group">
                        <label for="company">Select Company :</label>
                        <select class="form-select form-control" id="company" name="company_id">
                            <option selected>Select Company :</option>
                            @foreach ($companies as $key => $company)
                                <option value="{{$company->id}}" {{ $company->id == $employee->company_id ? 'selected' : '' }}>{{$company->name}}</option>
                            @endforeach
                        </select>
                    </div>
                  
                  <div class="form-group">
                    <label for="email">Email address :</label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" value="{{ old('email', $employee->email) }}">
                  </div>
                  <div class="form-group">
                    <label for="phone">Phone :</label>
                    <input type="number" class="form-control" name="phone" id="phone" placeholder="enter phone Number" value="{{ old('phone', $employee->phone) }}">
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
@endsection

resources/views/employees/index.blade.php
@extends('layout.master')
@section('title', 'Employees List')
@section('main')
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Employees List</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('employees.index')}}">List</a></li>
            <li class="breadcrumb-item active">List Of Employees</li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="content">
    <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              {{-- <div class="card-header">
                <h3 class="card-title">DataTable with minimal features & hover style</h3>
              </div> --}}
              <!-- /.card-header -->
              <div class="card-body">
                <table>
                    <table id="dataTable" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Sr No</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Company Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($employees as $key => $employee)    
                                <tr>
                                    <td>{{$key + 1 }}</td>
                                    <td>{{$employee->first_name}}</td>
                                    <td>{{$employee->last_name}}</td>
                                    <td>{{$employee->company->name}}</td>
                                    <td>{{$employee->email}}</td>
                                    <td>{{$employee->phone}}</td>
                                    <td>
                                        <a href="{{url("employees/")}}/{{$employee->id}}/edit" class="btn btn-sm btn-outline-primary me-1"><i class="far fa-edit nav-icon"></i></a>
                                        <a href="javascript:;" class="btn btn-sm btn-outline-danger" onclick="deleteEmployee({{$employee->id}})"><i class="fa fa-trash nav-icon"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                </table>
              </div>
            </div>
        </div>
    </div>
  </section>

@endsection

@section('script')
    @if(Session::has('add_message'))    
        <script>
            Toast.fire({
                icon: 'success',
                title: 'Employee Added Successfully.'
            });
        </script>
    @endif
    @if(Session::has('update_message'))
        <script>
            Toast.fire({
                icon: 'success',
                title: 'Employee Updated Successfully.'
            });
        </script>
    @endif

    <script>
         var dataTable;
        $(document).ready(function(){
           dataTable = $('#dataTable').DataTable();
        });

        function deleteEmployee(id) {
            var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
            });
            if(confirm('Are you sure you want to delete!'))
            {
                $.ajax({
                    url: "employees/" + id,
                    type: "DELETE",
                    data: {
                        _token: "{{ csrf_token() }}"
                    },
                    success: function(response) {
                        if (response.error_message) {
                            Toast.fire({
                                icon: 'error',
                                title: 'Contact Admin! Somthing went wrong.'
                            });
                        }
                        else {
                            Toast.fire({
                                icon: 'success',
                                title: 'Employee Updated Successfully.'
                            });
                            setTimeout(function(){
                                window.location.reload();
                            }, 2500);
                        }
                    }
                });
            }
        }
    </script>
@endsection